# .circleci/config.yml
version: 2.1

orbs:
  path-filtering: circleci/path-filtering@1.1.0
  continuation: circleci/continuation@1.0.0

setup: true

workflows:
  main:
    jobs:
      - path-filtering/filter:
          name: determine-changes
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            server/* CONFIG_FILE .circleci/server-config.yml
            web-portal/* CONFIG_FILE .circleci/web-portal-config.yml
