version: 2.1

parameters:
  run_server:
    type: boolean
    default: false
  run_web_portal:
    type: boolean
    default: false

jobs:
  debug-config:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: Print Config Status
          command: |
            echo "Server triggered: << pipeline.parameters.run_server >>"
            echo "Web Portal triggered: << pipeline.parameters.run_web_portal >>"

workflows:
  run-configs:
    jobs:
      - when:
          condition: << pipeline.parameters.run_server >>
          steps:
            - continuation/continue:
                configuration_path: .circleci/server-config.yml
      - when:
          condition: << pipeline.parameters.run_web_portal >>
          steps:
            - continuation/continue:
                configuration_path: .circleci/web-portal-config.yml
