# .circleci/continue_config.yml
version: 2.1

parameters:
  CONFIG_FILE:
    type: string
    default: ""

jobs:
  debug-config:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: Print Config File
          command: |
            echo "Using config file: << pipeline.parameters.CONFIG_FILE >>"

workflows:
  run-config:
    when:
      not:
        equal: [ "", << pipeline.parameters.CONFIG_FILE >> ]
    jobs:
      - debug-config
      - continuation/continue:
          configuration_path: << pipeline.parameters.CONFIG_FILE >>
